# numpy

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = [[1,2,3],
    [4,5,6]]

In [10]:
array = np.array(a, dtype=np.float32)

In [12]:
array.dtype

dtype('float32')

In [7]:
array.shape

(2, 3)

In [8]:
# 是一个几维数组
array.ndim

2

In [9]:
# 数组中有多少个元素
array.size

6

In [14]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
np.ones((3,4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [18]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [19]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.linspace(1, 5, 10) # 起始值，终值，生成多少个数

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [23]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)

In [24]:
a+b

array([10, 21, 32, 43])

In [25]:
a-b

array([10, 19, 28, 37])

In [26]:
a*b

array([  0,  20,  60, 120])

In [27]:
b**2

array([0, 1, 4, 9])

In [28]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [29]:
x1 = a.reshape((2,2))
x2 = b.reshape((2,2))

In [30]:
# 矩阵逐个相乘
x1*x2

array([[  0,  20],
       [ 60, 120]])

In [33]:
# 矩阵乘法
np.dot(x1, x2)

array([[ 40,  70],
       [ 80, 150]])

In [34]:
x1.dot(x2)

array([[ 40,  70],
       [ 80, 150]])

In [37]:
np.random.random((2,4))

array([[ 0.50130713,  0.11126562,  0.93145786,  0.79182611],
       [ 0.22145226,  0.60212117,  0.95966026,  0.78302035]])

In [38]:
x2

array([[0, 1],
       [2, 3]])

In [39]:
np.sum(x2, axis=0) # 对每一列求和

array([2, 4])

In [40]:
np.sum(x2, axis=1) # 对每一行求和

array([1, 5])

In [42]:
np.min(x2, axis=1)

array([0, 2])

In [43]:
A = np.arange(15).reshape(3,5)

In [46]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
np.argmin(A)

0

In [47]:
np.mean(A, axis=1)

array([  2.,   7.,  12.])

In [48]:
np.median(A) # 中位数

7.0

In [49]:
A.T # 转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [50]:
np.clip(A, 3, 10) # 小于3的都变成3，大于10的都变成10

array([[ 3,  3,  3,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 10, 10, 10, 10]])

In [51]:
A[:,1]

array([ 1,  6, 11])

In [55]:
for i in A.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [56]:
A.flat #  这是一个迭代器

In [57]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
A = np.array([1,1,1])
B = np.array([2,2,2])

In [59]:
np.vstack((A,B)) # 上下合并

array([[1, 1, 1],
       [2, 2, 2]])

In [60]:
np.hstack((A,B)) # 相当于串联

array([1, 1, 1, 2, 2, 2])

In [61]:
A.shape

(3,)

In [62]:
A[:, np.newaxis].shape

(3, 1)

In [64]:
A = np.ones((2,4))
B = np.ones((1,4))

In [67]:
np.concatenate((A,B), axis=0) #在列方向上合并

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

# 矩阵分割

In [2]:
A = np.arange(12).reshape((3,4))

In [3]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.split(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [71]:
np.vsplit(A, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [72]:
np.hsplit(A, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

#  numpy中的copy和deepcopy

In [73]:
a = np.array([1,2,3,4])
b = a

In [74]:
a[0] = 666

In [75]:
a

array([666,   2,   3,   4])

In [76]:
b

array([666,   2,   3,   4])

In [77]:
b = a.copy() # deep copy

In [78]:
a[0] = 888

In [79]:
a

array([888,   2,   3,   4])

In [80]:
b

array([666,   2,   3,   4])